baseURL = "http://pentestdoc.com"
languageCode = "en-us"
buildDrafts = false
enableEmoji = true

author = "Pentester"
title = "PentestDoc | Pentest now !"
theme = "pentestdoc"
paginate = 6

[menu]
  [[menu.main]]
    name                   = "Vulns"
    identifier             = "vuln"
    url                    = "/vuln/"
    weight                 = 1

  [[menu.main]]
    name                   = "Pentest"
    identifier             = "pentest"
    url                    = "/pentest/"
    weight                 = 2

  [[menu.main]]
    name                   = "Tools"
    identifier             = "tool"
    url                    = "/tool/"
    weight                 = 3

  [[menu.main]]
    name                   = "Cheats"
    identifier             = "cheatsheet"
    url                    = "/cheatsheet/"
    weight                 = 4

    [[menu.main]]
    name                   = "Links"
    identifier             = "link"
    url                    = "/link/"
    weight                 = 5

[params]
  homeTitle = "PentestDoc"
  description = "Pentestdoc.com"
  keywords = ""


[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  platform = "platforms"
  interface = "interfaces"
  license = "licenses"
  programlang = "programlangs"
  vulntype = "vulntypes"